version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - nilerr
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testpackage
    - tparallel
    - unparam
    - unused
    - wastedassign
  settings:
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
        - diagnostic
        - style
      settings:
        hugeParam:
          sizeThreshold: 256
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
